name: lausanne-agglom-extent
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
    - urban-footprinter==0.2.0
  - setuptools
  - wheel
  - click
  - flake8
  - awscli
  - python-dotenv>=0.5.1
  - python=3
  - ipykernel
  - boto3
  - tqdm
  - numpy
  - scipy
  - pandas
  - rasterio
  - shapely
  - geopandas
  - contextily
  - descartes
